select top 20 * from customer
--what is the total revenue generated by male vs female customer
select gender, sum(purchase_amount) as total_amount
from customer
group by gender

-- which customer used discount but still spent more then average purchase_amount
select customer_id,purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount>(select avg(purchase_amount) from customer)

--which are the top 5 products with the highest average review rating
select top 5 item_purchased,round(AVG(review_rating),2) as avg_review_rating
from customer
group by item_purchased
order by avg_review_rating desc

-- compare the average purchase amount between standard and Express shipping
select shipping_type , avg(purchase_amount) as avg_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--do subcribed Customer spent more? compare average coustomer and total customer spent between subcriber and non-subcriber
select subscription_status, count(customer_id) as total_customer,
avg(purchase_amount) as avg_amount,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg_amount,total_revenue desc

--Which 5 products have the highest percentage of perchases with the discount applied
select top 5 item_purchased, 
round(100*sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) discount_percentage
from customer
group by item_purchased
order by discount_percentage

--Segment customers into New,Returning and Loyal based on there previous purchase and show the count of each customer
with customer_type as (
select customer_id, previous_purchases,
case
   when previous_purchases = 1 then 'New' 
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
end customer_segment
from  customer
)
select customer_segment, count(*) as Number_of_customer
from customer_type
group by customer_segment;

--what are the top 3 purchase products in each category
with item_count as (
select category,
item_purchased,
count(customer_id) as total_order,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) item_rank 
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_order
from item_count
where item_rank <=3;

--Are customers who are repeat buyers(more than 5 previous purchase)also likly to subcribe
select subscription_status ,
count(customer_id) as repeat_customer
from customer
where previous_purchases>5
group by subscription_status;

--What is the revenue contribution of each group
select age_group, sum(purchase_amount) as  total_revenue
from customer
group by age_group
order by total_revenue desc;